name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "alberto.lopezbastos@gmail.com"
        git config --global user.name "AlbertoLopezBastos"
        git remote set-url origin https://git: https://github.com/ on DESKTOP-E26IM5C at 16-ago.-2020 22:03@github.com/AlbertoLopezBastos/movies>.git
        npm run deploy
