name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: AlbertoLopezBastos/movies@master
        env:
          ACCESS_TOKEN: ${{ secrets.REACT_APP_API_KEY }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm run build
