name: Build and Deploy to GitHub Pages on Push

on:
 push:
  - branches:
     - master

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Build and Deploy
     uses: AlbertoLopezBastos/movies@master
     env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
